Repository ansible-collections/kubernetes.core, pull requests merged in 2024-06, with the labels that each got.

#741 Doc: add example of using kubectl connection plugin
  .ansible-lint-ignore
  changelogs/fragments/20240601-doc-example-of-using-kubectl.yaml
  docs/kubernetes.core.kubectl_connection.rst
  plugins/connection/kubectl.py
Labels: mergeit, backport-3, backport-5

#733 Prepare release 5.0.0
  CHANGELOG.rst
  Makefile
  README.md
  changelogs/changelog.yaml
  changelogs/fragments/20240530-ansible-core-support-update.yaml
  changelogs/fragments/20240530-defer-removal-and-ansible-core-support-update.yaml
  docs/kubernetes.core.k8s_inventory.rst
  galaxy.yml
Labels: test-all-the-targets, skip-changelog

#747 Update changelog after release 5.0.0
  CHANGELOG.rst
  Makefile
  README.md
  changelogs/changelog.yaml
  changelogs/fragments/20231206-fix-unsafe-condition-in-integration.yml
  changelogs/fragments/20240117-fix-helm-diff-cmd-line-rendering.yml
  changelogs/fragments/20240222-Collections-util-resource-discovery-fails-when-complex-subresources-present.yml
  changelogs/fragments/20240228-fix-helm-diff-with-reuse-values.yml
  changelogs/fragments/20240423-k8s-display-warnings-to-users.yml
  changelogs/fragments/20240530-ansible-core-support-update.yaml
  changelogs/fragments/20240530-defer-removal-and-ansible-core-support-update.yaml
  changelogs/fragments/20240601-doc-example-of-using-kubectl.yaml
  changelogs/fragments/inventory-update_removal_date.yml
  changelogs/fragments/k8s-merge_type-removed.yml
  changelogs/fragments/module_utils-common-remove-deprecated-functions-and-class.yaml
  docs/kubernetes.core.k8s_inventory.rst
  docs/kubernetes.core.k8s_module.rst
  galaxy.yml
Labels: mergeit, test-all-the-targets, skip-changelog

#746 Prepare version 3.2.0
  CHANGELOG.rst
  Makefile
  README.md
  changelogs/changelog.yaml
  changelogs/fragments/20240601-doc-example-of-using-kubectl.yaml
  docs/kubernetes.core.k8s_inventory.rst
  galaxy.yml
Labels: mergeit

#745 helm: Accept release candidate versions for compatibility checks
  changelogs/fragments/20240611-helm-rc-version.yaml
  plugins/module_utils/helm.py
  tests/unit/module_utils/test_helm.py
Labels: mergeit, backport-3, backport-5

#750 Doc: update changelog with release 3.2.0
  CHANGELOG.rst
Labels: mergeit

#749 fix shields.io badges in README.md
  README.md
Labels: mergeit
