Repository ansible-collections/kubernetes.core, pull requests merged in 2024-12, with the labels that each got.

#793 Fix k8s_drain runs into timeout with pods from stateful sets.
  changelogs/fragments/793-fix-k8s-drain-runs-into-timeout.yaml
  plugins/module_utils/helm.py
  plugins/modules/k8s_drain.py
Labels: mergeit, backport-3, backport-5

#798 Improve error message for pod disruption budget when draining a node
  changelogs/fragments/798-drain-pdb-error-message.yaml
  plugins/modules/k8s_drain.py
Labels: mergeit, backport-3, backport-5

#823 Backport to stable-5: README: Add Communication section with Forum information (#774)
  README.md
  changelogs/fragments/0-readme.yml
Labels: mergeit

#827 Fix helm tests
  tests/integration/targets/helm/tasks/main.yml
  tests/integration/targets/helm/tasks/test_helm_reuse_values.yml
  tests/integration/targets/helm/tasks/tests_chart.yml
  tests/integration/targets/helm_pull/tasks/main.yml
  tests/integration/targets/helm_set_values/tasks/main.yml
  tests/integration/targets/install_helm/defaults/main.yml
Labels: mergeit, test-all-the-targets, skip-changelog, backport-3, backport-5

#830 Fix helm integration tests
  tests/integration/targets/helm_diff/files/test-chart-deployment-time/Chart.yaml
  tests/integration/targets/helm_diff/files/test-chart-deployment-time/templates/configmap.yaml
  tests/integration/targets/helm_diff/meta/main.yml
  tests/integration/targets/helm_diff/tasks/main.yml
  tests/integration/targets/helm_kubeconfig/tasks/tests_helm_auth.yml
  tests/integration/targets/push_to_helm_registry/aliases
  tests/integration/targets/push_to_helm_registry/defaults/main.yml
  tests/integration/targets/push_to_helm_registry/tasks/main.yml
  tests/integration/targets/setup_helm_registry/aliases
  tests/integration/targets/setup_helm_registry/defaults/main.yml
  tests/integration/targets/setup_helm_registry/handlers/main.yml
  tests/integration/targets/setup_helm_registry/tasks/main.yml
  tests/integration/targets/setup_helm_registry/tasks/remove_docker_container.yml
  tests/integration/targets/setup_helm_registry/tasks/teardown_registry.yml
  tests/sanity/ignore-2.14.txt
  tests/sanity/ignore-2.15.txt
  tests/sanity/ignore-2.16.txt
  tests/sanity/ignore-2.17.txt
  tests/sanity/ignore-2.18.txt
  tests/sanity/ignore-2.19.txt
Labels: mergeit, test-all-the-targets, skip-changelog, backport-3, backport-5

#804 fix: typo
  plugins/modules/k8s_drain.py
Labels: skip-changelog

#805 Parameter insecure_registry added to helm_template
  changelogs/fragments/20241207-add-insecure-skip-tls-verify-to-helm-template.yaml
  docs/kubernetes.core.helm_template_module.rst
  plugins/modules/helm_template.py
Labels: test-all-the-targets

#800 helm_registry_auth module to authenticate in OCI registry
  README.md
  docs/kubernetes.core.helm_registry_auth_module.rst
  plugins/module_utils/helm.py
  plugins/modules/helm_registry_auth.py
  tests/integration/targets/helm_registry_auth/aliases
  tests/integration/targets/helm_registry_auth/defaults/main.yaml
  tests/integration/targets/helm_registry_auth/files/registry.password
  tests/integration/targets/helm_registry_auth/meta/main.yml
  tests/integration/targets/helm_registry_auth/playbook.yaml
  tests/integration/targets/helm_registry_auth/runme.sh
  tests/integration/targets/helm_registry_auth/tasks/main.yaml
  tests/sanity/ignore-2.14.txt
  tests/sanity/ignore-2.15.txt
  tests/sanity/ignore-2.16.txt
  tests/sanity/ignore-2.17.txt
  tests/sanity/ignore-2.18.txt
  tests/sanity/ignore-2.19.txt
  tests/unit/module_utils/test_helm.py
  tests/unit/modules/test_helm_template_module.py
  tests/unit/modules/test_module_helm.py
Labels: test-all-the-targets, skip-changelog, backport-5

#826 Remove kubeconfig value from module invocation log
  changelogs/fragments/20241213-kubeconfig-set-no_log-true.yaml
  plugins/module_utils/args_common.py
  plugins/module_utils/helm_args_common.py
Labels: test-all-the-targets, backport-3, backport-5
