Repository ansible-collections/kubernetes.core, pull requests merged in 2024-05, with the labels that each got.

#701 k8s: Display warnings to users
  changelogs/fragments/20240423-k8s-display-warnings-to-users.yml
  plugins/module_utils/apply.py
  plugins/module_utils/k8s/runner.py
  plugins/module_utils/k8s/service.py
  tests/unit/module_utils/test_runner.py
  tests/unit/module_utils/test_service.py
Labels: mergeit, test-all-the-targets

#702 add support of kubectl_local_env_vars (#698)
  changelogs/fragments/20240426-add-support-of-kubectl-local-env-vars-for-connection-plugin.yml
  docs/kubernetes.core.kubectl_connection.rst
  plugins/connection/kubectl.py
Labels: mergeit, test-all-the-targets, backport-3

#704 Add tests/sanity/ignore-2.18.txt
  tests/sanity/ignore-2.18.txt
Labels: mergeit, backport-3

#707 Update ansible-lint GHA
  .github/workflows/linters.yaml
Labels: mergeit, skip-changelog, backport-3, backport-2

#592 Update kustomize.py add --enable-helm support
  changelogs/fragments/592-kustomize-helm-support.yml
  docs/kubernetes.core.kustomize_lookup.rst
  plugins/lookup/kustomize.py
Labels: mergeit, backport-3

#652 fixed typo in filename of 'k8s_json_patch'-action
  changelogs/fragments/652-fix-json-patch-action.yml
  plugins/action/k8s_json_patch.py
Labels: mergeit, backport-3

#703 minor(doc): use the same style of version_added across repo
  plugins/doc_fragments/helm_common_options.py
  plugins/doc_fragments/k8s_delete_options.py
  plugins/lookup/kustomize.py
  plugins/modules/helm.py
  plugins/modules/helm_info.py
  plugins/modules/helm_plugin.py
  plugins/modules/helm_plugin_info.py
  plugins/modules/helm_pull.py
  plugins/modules/helm_repository.py
  plugins/modules/helm_template.py
  plugins/modules/k8s_cluster_info.py
  plugins/modules/k8s_cp.py
  plugins/modules/k8s_drain.py
  plugins/modules/k8s_exec.py
  plugins/modules/k8s_log.py
  plugins/modules/k8s_rollback.py
  plugins/modules/k8s_taint.py
Labels: mergeit, skip-changelog

#716 Fix unsafe text assertion in tests
  tests/integration/targets/k8s_info/tasks/wait.yml
Labels: mergeit

#717 [Manual backport/stable-3] Fix unsafe text assertion in tests (#716)
  tests/integration/targets/k8s_info/tasks/wait.yml
Labels: mergeit

#700 Update deprecation version for merge_type=json
  plugins/modules/k8s.py
Labels: mergeit, skip-changelog, backport-3

#719 Release 3.1.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/20240426-add-support-of-kubectl-local-env-vars-for-connection-plugin.yml
  changelogs/fragments/592-kustomize-helm-support.yml
  changelogs/fragments/652-fix-json-patch-action.yml
  changelogs/fragments/654-helm-expand-user.yml
  docs/kubernetes.core.k8s_module.rst
  docs/kubernetes.core.kustomize_lookup.rst
  galaxy.yml
Labels: mergeit, test-all-the-targets, skip-changelog

#720 Sync stable-3 to main branch (#719)
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/20240426-add-support-of-kubectl-local-env-vars-for-connection-plugin.yml
  changelogs/fragments/592-kustomize-helm-support.yml
  changelogs/fragments/652-fix-json-patch-action.yml
  changelogs/fragments/654-helm-expand-user.yml
  docs/kubernetes.core.k8s_module.rst
  docs/kubernetes.core.kustomize_lookup.rst
  galaxy.yml
Labels: mergeit

#722 k8s - remove support for merge_type=json
  changelogs/fragments/k8s-merge_type-removed.yml
  plugins/module_utils/k8s/service.py
  plugins/modules/k8s.py
Labels: mergeit

#723 Defer removal of k8s inventory plugin to version 5.0.
  changelogs/fragments/inventory-update_removal_date.yml
  meta/runtime.yml
  plugins/inventory/k8s.py
Labels: mergeit, backport-3

#726 Remove deprecated function from module_utils/common.py
  changelogs/fragments/module_utils-common-remove-deprecated-functions-and-class.yaml
  plugins/inventory/k8s.py
  plugins/module_utils/common.py
  plugins/modules/k8s_exec.py
Labels: mergeit, test-all-the-targets

#727 Prepare release 4.0.0
  CHANGELOG.rst
  Makefile
  README.md
  changelogs/changelog.yaml
  changelogs/fragments/20231206-fix-unsafe-condition-in-integration.yml
  changelogs/fragments/20240117-fix-helm-diff-cmd-line-rendering.yml
  changelogs/fragments/20240222-Collections-util-resource-discovery-fails-when-complex-subresources-present.yml
  changelogs/fragments/20240228-fix-helm-diff-with-reuse-values.yml
  changelogs/fragments/20240423-k8s-display-warnings-to-users.yml
  changelogs/fragments/inventory-update_removal_date.yml
  changelogs/fragments/k8s-merge_type-removed.yml
  changelogs/fragments/module_utils-common-remove-deprecated-functions-and-class.yaml
  docs/kubernetes.core.k8s_inventory.rst
  docs/kubernetes.core.k8s_module.rst
  galaxy.yml
Labels: test-all-the-targets, skip-changelog

#731 kubevirt.core collection cross testing
  .github/workflows/integration-tests-kubevirt.yaml
  tools/kubevirt_list_targets.py
Labels: mergeit, skip-changelog, backport-3, backport-2, backport-4

#734 Defer removal of inventory/k8s to 6.0.0
  changelogs/fragments/20240530-ansible-core-support-update.yaml
  meta/runtime.yml
  plugins/inventory/k8s.py
Labels: mergeit, backport-3, backport-5

#737 Drop support for ansible-core<2.15
  README.md
  changelogs/fragments/20240530-defer-removal-and-ansible-core-support-update.yaml
  meta/runtime.yml
Labels: mergeit, backport-5
