Repository ansible-collections/kubernetes.core, pull requests merged in 2024-07, with the labels that each got.

#757 Remove ansible install step from kubevirt GHA
  .github/workflows/integration-tests-kubevirt.yaml
Labels: mergeit, backport-3, backport-5

#756 Fix waiting for daemonset when desired number of pods is 0
  changelogs/fragments/756-fix-daemonset-waiting.yaml
  plugins/module_utils/k8s/waiter.py
  tests/integration/targets/k8s_waiter/defaults/main.yml
  tests/integration/targets/k8s_waiter/tasks/main.yml
Labels: mergeit, test-all-the-targets

#765 Bump the ansible-lint version to 24.7.0
  .github/workflows/linters.yaml
  changelogs/fragments/765-bump-ansible-lint-version.yml
Labels: mergeit

#767 Update Readme to match the template
  README.md
  changelogs/fragments/readme_template_update.yml
Labels: mergeit
