Repository ansible-collections/kubernetes.core, pull requests merged in 2024-03, with the labels that each got.

#691 Prepare release 2.4.2
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/20240222-Collections-util-resource-discovery-fails-when-complex-subresources-present.yml
  tests/integration/targets/helm_kubeconfig/tasks/main.yml
Labels: test-all-the-targets, skip-changelog

#693 Prepare release 3.0.1
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/20240117-fix-helm-diff-cmd-line-rendering.yml
  changelogs/fragments/20240222-Collections-util-resource-discovery-fails-when-complex-subresources-present.yml
  changelogs/fragments/20240228-fix-helm-diff-with-reuse-values.yml
Labels: test-all-the-targets

#654 helm - expand kubeconfig path with user's home dir
  changelogs/fragments/654-helm-expand-user.yml
  plugins/module_utils/helm.py
Labels: mergeit, backport-3, backport-2

#696 [backport/stable-2.4] helm - expand kubeconfig path with user's home dir (#654)
  changelogs/fragments/654-helm-expand-user.yml
  plugins/module_utils/helm.py
Labels: mergeit
