Repository ansible-collections/kubernetes.core, pull requests merged in 2025-04, with the labels that each got.

#896 Cherry pick 5.2.0 release into main (#891)
  CHANGELOG.rst
  README.md
  changelogs/changelog.yaml
  changelogs/fragments/643-extend-hidden-fields.yaml
  changelogs/fragments/879-clusteroperator-waiter.py.yaml
Labels: mergeit

#905 Rebase PR #898
  changelogs/fragments/898-k8s-dont-delete-in-check-mode.yaml
  plugins/module_utils/k8s/service.py
  tests/integration/targets/k8s_delete/tasks/main.yml
Labels: mergeit, backport-3, backport-5

#911 [PR #903/d4fc22c7 backport][stable-3] Bugfix: fix unit-source for pre-release of ansible-core 2.20 (devel and milestone branch)
  tests/unit/module_utils/test_core.py
Labels: mergeit, skip-changelog

#802 add reset_then_reuse_values support to helm module
  changelogs/fragments/800-helm-add-reset_then_reuse_values-support.yml
  docs/kubernetes.core.helm_module.rst
  plugins/modules/helm.py
  tests/integration/targets/helm/defaults/main.yml
  tests/integration/targets/helm/tasks/main.yml
  tests/integration/targets/helm/tasks/run_test.yml
  tests/integration/targets/helm/tasks/test_helm_reset_then_reuse_values.yml
  tests/integration/targets/helm_diff/tasks/main.yml
  tests/integration/targets/helm_diff/tasks/reset_then_reuse_values.yml
  tests/integration/targets/helm_diff/tasks/reuse_values.yml
  tests/integration/targets/install_helm/defaults/main.yml
Labels: mergeit, backport-3, backport-5

#919 Update ansible-lint version to 25.1.2
  .github/workflows/linters.yaml
  changelogs/fragments/919-update-ansible-lint-version.yaml
Labels: mergeit, backport-3, backport-5

#867 Initial update to 6.0.0-dev0: remove support of ansible-core<2.16.0 and k8s inventory plugin
  Makefile
  README.md
  changelogs/fragments/20250121-breaking-changes-6.0.0.yml
  docs/docsite/rst/kubernetes_scenarios/k8s_intro.rst
  docs/docsite/rst/kubernetes_scenarios/k8s_inventory.rst
  docs/docsite/rst/scenario_guide.rst
  docs/kubernetes.core.k8s_drain_module.rst
  docs/kubernetes.core.k8s_inventory.rst
  galaxy.yml
  meta/runtime.yml
  plugins/inventory/k8s.py
  tests/integration/targets/inventory_k8s/aliases
  tests/integration/targets/inventory_k8s/playbooks/create_resources.yml
  tests/integration/targets/inventory_k8s/playbooks/delete_resources.yml
  tests/integration/targets/inventory_k8s/playbooks/play.yml
  tests/integration/targets/inventory_k8s/playbooks/test.inventory_k8s.yml
  tests/integration/targets/inventory_k8s/playbooks/vars/main.yml
  tests/integration/targets/inventory_k8s/runme.sh
  tests/sanity/ignore-2.15.txt
  tests/sanity/ignore-2.20.txt
Labels: mergeit
