Repository ansible-collections/kubernetes.core, pull requests merged in 2025-06, with the labels that each got.

#939 Fix unit tests with ansible-core 2.19
  changelogs/fragments/20250503-fix-unit-tests.yml
  tests/unit/module_utils/test_core.py
Labels: mergeit, backport-5

#941 Update `dev` version to `7.0.0-dev0` after `6.0.0` release
  Makefile
  galaxy.yml
Labels: mergeit, skip-changelog

#936 Add automatic labeling for new triage issues
  .github/workflows/label-new-issues.yaml
Labels: mergeit

#934 Add `plain_http` parameter to `helm`, `helm_pull` and `helm_template`
  changelogs/fragments/20250522-add-plain-http-for-oci-registries.yaml
  docs/kubernetes.core.helm_module.rst
  docs/kubernetes.core.helm_pull_module.rst
  docs/kubernetes.core.helm_template_module.rst
  plugins/modules/helm.py
  plugins/modules/helm_pull.py
  plugins/modules/helm_template.py
  tests/integration/targets/helm_plain_http/aliases
  tests/integration/targets/helm_plain_http/inventory.ini
  tests/integration/targets/helm_plain_http/playbooks/play.yaml
  tests/integration/targets/helm_plain_http/playbooks/tasks/test.yaml
  tests/integration/targets/helm_plain_http/runme.sh
Labels: mergeit, backport-6
