Repository ansible-collections/kubernetes.core, pull requests merged in 2025-01, with the labels that each got.

#829 Backport to Stable-3: Fix helm tests (#827) and Fix helm integration tests (#830)
  tests/integration/targets/helm/tasks/main.yml
  tests/integration/targets/helm/tasks/test_helm_reuse_values.yml
  tests/integration/targets/helm/tasks/tests_chart.yml
  tests/integration/targets/helm_diff/files/test-chart-deployment-time/Chart.yaml
  tests/integration/targets/helm_diff/files/test-chart-deployment-time/templates/configmap.yaml
  tests/integration/targets/helm_diff/meta/main.yml
  tests/integration/targets/helm_diff/tasks/main.yml
  tests/integration/targets/helm_kubeconfig/tasks/tests_helm_auth.yml
  tests/integration/targets/helm_pull/tasks/main.yml
  tests/integration/targets/helm_set_values/tasks/main.yml
  tests/integration/targets/install_helm/defaults/main.yml
  tests/integration/targets/push_to_helm_registry/aliases
  tests/integration/targets/push_to_helm_registry/defaults/main.yml
  tests/integration/targets/push_to_helm_registry/tasks/main.yml
  tests/integration/targets/setup_helm_registry/aliases
  tests/integration/targets/setup_helm_registry/defaults/main.yml
  tests/integration/targets/setup_helm_registry/handlers/main.yml
  tests/integration/targets/setup_helm_registry/tasks/main.yml
  tests/integration/targets/setup_helm_registry/tasks/remove_docker_container.yml
  tests/integration/targets/setup_helm_registry/tasks/teardown_registry.yml
  tests/sanity/ignore-2.14.txt
  tests/sanity/ignore-2.15.txt
  tests/sanity/ignore-2.16.txt
  tests/sanity/ignore-2.17.txt
  tests/sanity/ignore-2.18.txt
  tests/sanity/ignore-2.19.txt
Labels: mergeit, test-all-the-targets, skip-changelog

#848 fix linters issue in CI caused by uplift of ansible-compat
  .config/ansible-lint-ignore.txt
  .config/ansible-lint.yml
  .github/workflows/linters.yaml
Labels: mergeit, skip-changelog, backport-3, backport-5

#852 Clean up test namespace
  tests/integration/targets/helm_set_values/tasks/main.yml
Labels: mergeit, skip-changelog, backport-3, backport-5

#831 trivial doc: replace 2.5.0 with 3.0.0
  docs/kubernetes.core.helm_module.rst
  docs/kubernetes.core.k8s_drain_module.rst
  docs/kubernetes.core.k8s_info_module.rst
  docs/kubernetes.core.k8s_module.rst
  plugins/modules/helm.py
  plugins/modules/k8s.py
  plugins/modules/k8s_drain.py
  plugins/modules/k8s_info.py
Labels: mergeit, skip-changelog, backport-3, backport-5

#850 Backport "fix linters in github actions (#848)" to stable-3
  .config/ansible-lint-ignore.txt
  .config/ansible-lint.yml
  .github/workflows/linters.yaml
Labels: mergeit

#796 helm_pull: Silence false no_log warning
  changelogs/fragments/796-false-positive-helmull.yaml
  plugins/modules/helm_pull.py
  tests/integration/targets/helm_pull/tasks/main.yml
Labels: mergeit, backport-3, backport-5

#838 Remove deprecated .github/stale.yml to address #837
  .github/stale.yml
Labels: mergeit, skip-changelog, backport-3, backport-5

#863 Prepare release 3.3.0
  CHANGELOG.rst
  Makefile
  README.md
  changelogs/changelog.yaml
  changelogs/fragments/20240530-ansible-core-support-update.yaml
  changelogs/fragments/20240611-helm-rc-version.yaml
  changelogs/fragments/20240620-fix-kustomize-plugin-fails-with-deprecation-warnings.yml
  changelogs/fragments/20241102-fix-ci-post-2.18-issue.yaml
  changelogs/fragments/20241213-kubeconfig-set-no_log-true.yaml
  changelogs/fragments/756-fix-daemonset-waiting.yaml
  changelogs/fragments/770-fix-k8s-drain-doesnt-wait-for-single-pod.yaml
  changelogs/fragments/793-fix-k8s-drain-runs-into-timeout.yaml
  changelogs/fragments/796-false-positive-helmull.yaml
  changelogs/fragments/798-drain-pdb-error-message.yaml
  changelogs/fragments/inventory-update_removal_date.yml
  changelogs/fragments/readme_template_update.yml
  galaxy.yml
Labels: mergeit

#866 Post release 5.1.0 update
  CHANGELOG.rst
  Makefile
  README.md
  changelogs/changelog.yaml
  changelogs/fragments/0-readme.yml
  changelogs/fragments/20240611-helm-rc-version.yaml
  changelogs/fragments/20240620-fix-kustomize-plugin-fails-with-deprecation-warnings.yml
  changelogs/fragments/20241102-fix-ci-post-2.18-issue.yaml
  changelogs/fragments/20241103-completly-remove-obsolate-communication-channel.yaml
  changelogs/fragments/20241207-add-insecure-skip-tls-verify-to-helm-template.yaml
  changelogs/fragments/20241213-kubeconfig-set-no_log-true.yaml
  changelogs/fragments/756-fix-daemonset-waiting.yaml
  changelogs/fragments/765-bump-ansible-lint-version.yml
  changelogs/fragments/770-fix-k8s-drain-doesnt-wait-for-single-pod.yaml
  changelogs/fragments/793-fix-k8s-drain-runs-into-timeout.yaml
  changelogs/fragments/796-false-positive-helmull.yaml
  changelogs/fragments/798-drain-pdb-error-message.yaml
  changelogs/fragments/readme_template_update.yml
  galaxy.yml
Labels: mergeit
