Repository ansible-collections/kubernetes.core, pull requests merged in 2025-05, with the labels that each got.

#924 Run integration tests using ansible-core 2.19 (#888)
  .github/workflows/integration-tests.yaml
  changelogs/fragments/20250324-k8s_info-templating.yaml
  plugins/action/k8s_info.py
  tests/integration/targets/k8s_apply/tasks/main.yml
  tests/integration/targets/k8s_delete/tasks/main.yml
  tests/integration/targets/k8s_drain/tasks/main.yml
  tests/integration/targets/k8s_full/tasks/main.yml
  tests/integration/targets/k8s_gc/tasks/main.yml
  tests/integration/targets/k8s_json_patch/tasks/main.yml
  tests/integration/targets/k8s_scale/tasks/main.yml
  tests/integration/targets/k8s_taint/tasks/main.yml
  tests/integration/targets/k8s_template/tasks/main.yml
  tests/integration/targets/k8s_template/templates/configmap.yml.j2
  tests/integration/targets/lookup_k8s/tasks/main.yml
  tests/integration/targets/setup_namespace/tasks/main.yml
  tests/unit/action/test_remove_omit.py
Labels: skip-changelog

#901 Add helm insecure skip tls verify
  changelogs/fragments/694-add-insecure-skip-tls-verify.yml
  plugins/modules/helm.py
  plugins/modules/helm_pull.py
  plugins/modules/helm_repository.py
  tests/integration/targets/helm/defaults/main.yml
  tests/integration/targets/helm/tasks/main.yml
  tests/integration/targets/helm/tasks/run_test.yml
  tests/integration/targets/helm/tasks/test_crds.yml
  tests/integration/targets/helm/tasks/test_helm_insecure.yml
  tests/integration/targets/helm_repository/meta/main.yml
  tests/integration/targets/helm_repository/tasks/main.yml
Labels: mergeit

#926 Update `README` to communicate that `stable-4` is no longer supported
  README.md
Labels: type/documentation, mergeit, skip-changelog

#931 [Manual Backport][stable-5] Update `README` to communicate that `stable-4` is no longer supported #926
  README.md
Labels: type/documentation, mergeit, skip-changelog

#929 Prepare release 5.3.0
  CHANGELOG.rst
  README.md
  changelogs/changelog.yaml
  changelogs/fragments/20250324-k8s_info-templating.yaml
  changelogs/fragments/694-add-insecure-skip-tls-verify.yml
  changelogs/fragments/800-helm-add-reset_then_reuse_values-support.yml
  changelogs/fragments/898-k8s-dont-delete-in-check-mode.yaml
  changelogs/fragments/919-update-ansible-lint-version.yaml
  docs/kubernetes.core.helm_module.rst
  docs/kubernetes.core.helm_pull_module.rst
  docs/kubernetes.core.helm_repository_module.rst
  docs/kubernetes.core.k8s_drain_module.rst
  docs/kubernetes.core.k8s_info_module.rst
  docs/kubernetes.core.k8s_module.rst
  galaxy.yml
Labels: mergeit, test-all-the-targets, skip-changelog

#932 Push 5.x.x changes into main branch
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/20250324-k8s_info-templating.yaml
  changelogs/fragments/694-add-insecure-skip-tls-verify.yml
  changelogs/fragments/800-helm-add-reset_then_reuse_values-support.yml
  changelogs/fragments/898-k8s-dont-delete-in-check-mode.yaml
  changelogs/fragments/919-update-ansible-lint-version.yaml
Labels: mergeit
